/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'About',
    },
    {
      type: 'autogenerated',
      dirName: 'case-studies',
    },
    {
      type: 'autogenerated',
      dirName: 'writing-samples',
    },
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
  ],
};

module.exports = sidebars;
